// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrjeuofqbjujlxcontxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyamV1b2ZxYmp1amx4Y29udHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTQ1MjYsImV4cCI6MjA3MTAzMDUyNn0.KTT2XQtDjdrBNw4Ec0Hs9vFdUoW6pZrpmfZNhWUrVdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});